source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
# CocoaPods >= 1.13 requires Ruby >= 2.7
ruby ">= 2.7"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
# Listed alphabetically for RuboCop compliance.
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'xcodeproj', '!= 1.26.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
# Listed alphabetically for RuboCop compliance.
gem 'base64'
gem 'benchmark'
gem 'bigdecimal'
gem 'logger'
gem 'mutex_m'
gem 'nkf'
